all:	TestDLL TestStack calculator

TestDLL:	TestDLL.cpp
	g++ -std=c++11 -Wall TestDLL.cpp -o TestDLL
	
calculator:  calculator.cpp
	g++ -std=c++11 -Wall calculator.cpp -o calculator
	
TestStack:	TestStack.cpp
	g++ -std=c++11 -Wall TestStack.cpp -o TestStack
	
clean:
	rm TestDLL TestStack